/* oxlint-disable */
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core (Standard Schema)
// Do not edit manually — re-generated on every dev server start and build
// Tip: for richer types, use defineEnv() with Zod instead of defineStandardEnv()
// Server output types reflect the Valibot transforms in src/env.ts.

declare module 'virtual:env/client' {
  const env: {

  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly DATABASE_URL: string
    readonly DATABASE_AUTH_TOKEN?: string
    readonly PORT: number
  }
  export { env }
  export default env
}
