/* oxlint-disable */
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core (Standard Schema)
// Do not edit manually — re-generated on every dev server start and build
// Tip: for richer types, use defineEnv() with Zod instead of defineStandardEnv()

declare module 'virtual:env/client' {
  const env: {
    readonly VITE_POSTHOG_KEY: string
    readonly VITE_POSTHOG_HOST: string
    readonly VITE_TERMINAL_DELAY_MS: string
    readonly VITE_CART_IDLE_TIMEOUT_MS: string
    readonly VITE_CART_IDLE_COUNTDOWN_SECONDS: string
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly DATABASE_URL: string
    readonly PORT: string
    readonly VITE_POSTHOG_KEY: string
    readonly VITE_POSTHOG_HOST: string
    readonly VITE_TERMINAL_DELAY_MS: string
    readonly VITE_CART_IDLE_TIMEOUT_MS: string
    readonly VITE_CART_IDLE_COUNTDOWN_SECONDS: string
  }
  export { env }
  export default env
}
